'use strict';

var Primus = require('primus');

var config = require('./config');

module.exports = function install_primus(server) {
	var primus = new Primus(server, { transformer: config.primus.transformer });

	primus.save(__dirname + '/../../client/common/other_components/primus-client-autogenerated/primus.js');

	primus.on('connection', function (spark) {
		console.log('* primus : a client connected.');

		spark.on('data', function(data) {
			console.log('* primus : data received from client :', data);
		});
	});

};
